name: Build Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Check the Project Structure
        run: |
          echo "Current Directory:"
          pwd
          echo "List project contents:"
          ls -l


      - name: Generate Documentation
        run: doxygen .github/workflows/Doxyfile

      - name: List contents of docs/html
        run: ls -al ./docs/html/


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
