name: Doxygen Documentation

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Doxygen
        run: sudo apt-get install doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Folder containing the generated HTML docs
